---
name: 🍎 MacOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 0 */5 * *'
    
      
# TODO: probably create a nightly job

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      QGIS_VERSION: ${{ steps.get-version.outputs.QGIS_VERSION }}
      QGIS_VERSION_SHORT: ${{ steps.get-version.outputs.QGIS_VERSION_SHORT }}
      MICROMAMBA_PLATFORM: ${{ steps.get-version.outputs.MICROMAMBA_PLATFORM }}
    steps:
      - name: 🌾 Get latest version
        id: get-version
        shell: bash
        run: |
          QGIS_VERSION=$(conda search -c conda-forge -f qgis | grep py311 | tail -n 1 | tr -s ' ' | cut -f 2 -d ' ')
          QGIS_VERSION_SHORT=$(echo $QGIS_VERSION | cut -d'.'  -f 1,2)
          MICROMAMBA_PLATFORM=$(conda search -c conda-forge -f micromamba  | tail -n 1 | tr -s ' ' | cut -f 2 -d ' ')
          echo QGIS_VERSION=$QGIS_VERSION >> $GITHUB_OUTPUT
          echo QGIS_VERSION_SHORT=$QGIS_VERSION_SHORT >> $GITHUB_OUTPUT
          echo MICROMAMBA_PLATFORM=$MICROMAMBA_PLATFORM >> $GITHUB_OUTPUT

  package:
    name: Package for macOS
    runs-on: macos-15
    needs: get-version
    env:
      QGIS_VERSION: ${{ needs.get-version.outputs.QGIS_VERSION }}
      QGIS_VERSION_SHORT: ${{ needs.get-version.outputs.QGIS_VERSION_SHORT }}
      MICROMAMBA_PLATFORM: ${{ needs.get-version.outputs.MICROMAMBA_PLATFORM }}
    strategy:
      matrix:
        include:
          - architecture: 'arm64'
            conda_platform: 'osx-arm64'
    steps:
      - name: 🐣 Checkout
        uses: actions/checkout@v4

      - name: 🐣 Checkout Constructor
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: opengisch/constructor
          ref: qgis-bundling
          path: constructor

      - name: Prepare
        run: |
          sed -i '' "s/__ver__/$QGIS_VERSION/g" construct.yaml
          sed -i '' "s/__shortver__/$QGIS_VERSION_SHORT/g" construct.yaml


      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: "constructor"
          environment-file: "environment.yaml"

      - name: 📦 Package
        shell: pwsh
        run: |
          wget https://github.com/mamba-org/micromamba-releases/releases/download/2.0.8-0/micromamba-osx-arm64
          ls -al
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: 📦 Package_suite
        shell: pwsh
        run: |   
          conda build constructor
          ls -al  /Users/runner/miniconda3/envs/constructor/conda-bld/
          ls -al  /Users/runner/miniconda3/envs/constructor/conda-bld/osx-64/
          conda install /Users/runner/miniconda3/envs/constructor/conda-bld/osx-64/*.tar.bz2
          constructor --platform=${{ matrix.conda_platform }} --conda-exe=micromamba-osx-arm64  .

      - name: 📦 Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QGIS-${{ env.QGIS_VERSION }}-MacOSX-${{ matrix.architecture }}
          path: QGIS-${{ env.QGIS_VERSION }}-MacOSX-${{ matrix.architecture }}.pkg

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - get-version
      - package
    env:
      QGIS_VERSION: ${{ needs.get-version.outputs.QGIS_VERSION }}
      QGIS_VERSION_SHORT: ${{ needs.get-version.outputs.QGIS_VERSION_SHORT }}
      MICROMAMBA_PLATFORM: ${{ needs.get-version.outputs.MICROMAMBA_PLATFORM }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: QGIS-${{ env.QGIS_VERSION }}-MacOSX-arm64
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ env.QGIS_VERSION }}
          artifacts: "*.pkg"
          body: "See https://github.com/qgis/QGIS/releases"
          tag: ${{ env.QGIS_VERSION }}
          allowUpdates: True
